V1=87;
V2=3;
FH=81;
BG=86;
AH=11;
intensity=AH*0.01;
fs=40000;
t=0:1/fs:1-1/fs;
x=V1*sin(2*pi*(FH*100)*t)+V2*sin(2*pi*(BG*100)*t)+intensity*randn(size(t));
noise=intensity*randn(size(t));
s_power=(V1^2)/2+(V2^2)/2;
n_power=intensity^2;
%SNR=s_power/n_power
SNR=snr(x); %Another way to find intensity
noise=intensity;
defSNR=10*log10(s_power/n_power);
snrCompare=[SNR defSNR];
bandwidth=obw(x,fs)
signal_capacity1=bandwidth*log2(1+SNR);
signal_capacity2=bandwidth*log2(1+defSNR);
capacityCompare=[signal_capacity1 signal_capacity2]
approxDatarate1=floor(bandwidth*log2(1+SNR))
approxDatarate2=floor(bandwidth*log2(1+defSNR))
compareDatarate=[approxDatarate1 approxDatarate2]
approxlevel1=floor(2*(approxDatarate1/(2*bandwidth)))
approxlevel2=floor(2*(approxDatarate2/(2*bandwidth)))
compareLevel=[approxlevel1 approxlevel2]

